Attribute VB_Name = "DWNames"
Option Explicit
DefLng A-Z
Public MapNames(256) As String


Public Sub GetNames()
  If WhichGame = 1 Then GetDW1Names
  If WhichGame = 2 Then GetDW2Names
  If WhichGame = 3 Then GetDW3Names
  If WhichGame = 4 Then GetDW4Names
End Sub

Sub GetDW2Names()
MapNames(&H0) = "Fake Midenhall"
MapNames(&H1) = "Overworld"
MapNames(&H2) = "Midenhall Throne Room"
MapNames(&H3) = "Midenhall"
MapNames(&H4) = "Midenhall Prison"
MapNames(&H5) = "Leftwynne"
MapNames(&H6) = "Cannock"
MapNames(&H7) = "Hamlin"
MapNames(&H8) = "Hamlin Jail"
MapNames(&H9) = "Moonbrooke"
MapNames(&HA) = "Moonbrooke Cellar"
MapNames(&HB) = "Lianport"
MapNames(&HC) = "Tantegel"
MapNames(&HD) = "Tantegel King's Room"
MapNames(&HE) = "Tantegel Throne Room"
MapNames(&HF) = "Osterfair"
MapNames(&H10) = "Zahan"
MapNames(&H11) = "Tuhn"
MapNames(&H12) = "Tuhn Watergate"
MapNames(&H13) = "Wellgarth Surface"
MapNames(&H14) = "Wellgarth"
MapNames(&H15) = "Beran"
MapNames(&H16) = "Hargon's Castle"
MapNames(&H17) = "Hargon's Room"
MapNames(&H18) = "Charlock Throne Room"
MapNames(&H19) = "Eye of Malroth Shrine"
MapNames(&H1A) = "Underwater Pass Shrine"
MapNames(&H1B) = "Golden Key Teleport Shrine"
MapNames(&H1C) = "South Alefgard Shrine"
MapNames(&H1D) = "Forest Teleport Shrine"
MapNames(&H1E) = "Fire Monolith"
MapNames(&H1F) = "Last Refuge"
MapNames(&H20) = "Desert River Shrine"
MapNames(&H21) = "Rhone foothills Shrine"
MapNames(&H22) = "Shrine to Osterfair"
MapNames(&H23) = "Rubiss Shrine 1F"
MapNames(&H24) = "Rubiss Shrine B1"
MapNames(&H25) = "Rubiss Shrine B2"
MapNames(&H26) = "Rubiss Shrine B3"
MapNames(&H27) = "Rubiss Shrine B4"
MapNames(&H28) = "Rubiss Shrine B5"
MapNames(&H29) = "Rubiss Shrine Final"
MapNames(&H2A) = "Monolith of Zahan"
MapNames(&H2B) = "Underpass to Hamlin"
MapNames(&H2C) = "Silver Key Cave B1"
MapNames(&H2D) = "Silver Key Cave B2"
MapNames(&H2E) = "Lava Cave B1"
MapNames(&H2F) = "Lava Cave B2"
MapNames(&H30) = "Lava Cave B3"
MapNames(&H31) = "Lava Cave B4"
MapNames(&H32) = "Lava Cave B5"
MapNames(&H33) = "Lava Cave B6"
MapNames(&H34) = "Charlock Castle B1"
MapNames(&H35) = "Charlock Castle B2"
MapNames(&H36) = "Charlock Castle B3"
MapNames(&H37) = "Rhone Cave Hork Basement B1"
MapNames(&H38) = "Rhone Cave 1F"
MapNames(&H39) = "Rhone Cave 2F-A"
MapNames(&H3A) = "Rhone Cave 2F-B"
MapNames(&H3B) = "Rhone Cave 2F-C"
MapNames(&H3C) = "Rhone Cave 3F"
MapNames(&H3D) = "Rhone Cave 4F"
MapNames(&H3E) = "Rhone Cave 5F"
MapNames(&H3F) = "Rhone Cave 6F"
MapNames(&H40) = "Spring of Bravery"
MapNames(&H41) = "CRASH"
MapNames(&H42) = "CRASH"
MapNames(&H43) = "Alefgard Tunnel"
MapNames(&H44) = "Hargon's Tower 2F"
MapNames(&H45) = "Hargon's Tower 3F"
MapNames(&H46) = "Hargon's Tower 4F (Atlas)"
MapNames(&H47) = "Hargon's Tower 5F (Bazuzu)"
MapNames(&H48) = "Hargon's Tower 6F (Zarlox)"
MapNames(&H49) = "Moon Fragment Tower 1F"
MapNames(&H4A) = "Moon Fragment Tower 2F"
MapNames(&H4B) = "Moon Fragment Tower 3F"
MapNames(&H4C) = "Moon Fragment Tower 4F"
MapNames(&H4D) = "Moon Fragment Tower 5F"
MapNames(&H4E) = "Moon Fragment Tower 6F"
MapNames(&H4F) = "Moon Fragment Tower 7F"
MapNames(&H50) = "Lighthouse 1F"
MapNames(&H51) = "Lighthouse 2F"
MapNames(&H52) = "Lighthouse 3F"
MapNames(&H53) = "Lighthouse 4F"
MapNames(&H54) = "Lighthouse 5F"
MapNames(&H55) = "Lighthouse 6F"
MapNames(&H56) = "Lighthouse 7F"
MapNames(&H57) = "Lighthouse 8F"
MapNames(&H58) = "Wind Tower 1F"
MapNames(&H59) = "Wind Tower 2F"
MapNames(&H5A) = "Wind Tower 3F"
MapNames(&H5B) = "Wind Tower 4F"
MapNames(&H5C) = "Wind Tower 5F"
MapNames(&H5D) = "Wind Tower 6F"
MapNames(&H5E) = "Wind Tower 7F"
MapNames(&H5F) = "Wind Tower 8F"
MapNames(&H60) = "South Drakhorn 1F"
MapNames(&H61) = "South Drakhorn 2F"
MapNames(&H62) = "South Drakhorn 3F"
MapNames(&H63) = "South Drakhorn 4F"
MapNames(&H64) = "South Drakhorn 5F"
MapNames(&H65) = "South Drakhorn 6F"
MapNames(&H66) = "North Drakhorn 1F"
MapNames(&H67) = "North Drakhorn 2F"
MapNames(&H68) = "North Drakhorn 3F"
MapNames(&H69) = "North Drakhorn 4F"
MapNames(&H6A) = "North Drakhorn 5F"
MapNames(&H6B) = "North Drakhorn 6F"
MapNames(&H6C) = "North Drakhorn 7F"
MapNames(&H6D) = "CRASH"
MapNames(&H6E) = "CRASH"
MapNames(&H6F) = "CRASH"
MapNames(&H70) = "CRASH"
MapNames(&H71) = "CRASH"
MapNames(&H72) = "CRASH"
MapNames(&H73) = "CRASH"
MapNames(&H74) = "CRASH"
MapNames(&H75) = "CRASH"
MapNames(&H76) = "Glitched shrine"
MapNames(&H77) = "CRASH"
MapNames(&H78) = "CRASH"
MapNames(&H79) = "Weird Glitched Tower"
MapNames(&H7A) = "Another weird glitched Tower"
MapNames(&H7B) = "CRASH"
MapNames(&H7C) = "CRASH"
MapNames(&H7D) = "CRASH"
MapNames(&H7E) = "CRASH"
MapNames(&H7F) = "CRASH"

End Sub

Sub GetDW1Names()

End Sub

Sub GetDW3Names()

End Sub

Sub GetDW4Names()

End Sub
